keys:
  - &dn_server age1z6f643a6vqm7cqh6fna5dhmxfkgwxgqy8kg9s0vf9uxhaswtngtspmqsjw

creation_rules:
  - path_regex: system/dev/dn-server/secret.yaml
    key_groups:
      - age:
          - *dn_server
