keys:
  - &dn_server age1z6f643a6vqm7cqh6fna5dhmxfkgwxgqy8kg9s0vf9uxhaswtngtspmqsjw
  - &dn_pre7780 age1uvsvf5ljaezh5wze32p685kfentyle0l2mvysc67yvgct2h4850qqph9lv

creation_rules:
  - path_regex: system/dev/dn-server/secret.yaml
    key_groups:
      - age:
          - *dn_server
  - path_regex: system/dev/dn-pre7780/secret.yaml
    key_groups:
      - age:
          - *dn_pre7780
